

export const FETCH_EMISSIONS = 'FETCH_EMISSIONS';
export const REQUEST_EMISSIONS = 'REQUEST_EMISSIONS';
export const RECEIVE_EMISSIONS = 'RECEIVE_EMISSIONS';
export const INVALIDATE_EMISSIONS = 'INVALIDATE_EMISSIONS';

export const FETCH_STATISTICS = 'FETCH_STATISTICS';
export const REQUEST_STATISTICS = 'REQUEST_STATISTICS';
export const RECEIVE_STATISTICS = 'RECEIVE_STATISTICS';

export const START_SIMULATION = 'START_SIMULATION';
export const REQUEST_SIMULATION = 'REQUEST_SIMULATION';
export const RECEIVE_SIMULATION = 'RECEIVE_SIMULATION';
export const SIMULATION_ERROR = 'SIMULATION_ERROR';
export const SET_SIMULATION_PARAMETERS = 'SET_SIMULATION_PARAMETERS';


export const REQUEST_TRAFFIC = 'REQUEST_TRAFFIC';
export const FETCH_TRAFFIC = 'FETCH_TRAFFIC';
export const RECEIVE_TRAFFIC = 'RECEIVE_TRAFFIC';
export const INVALIDATE_TRAFFIC = 'INVALIDATE_TRAFFIC';