

export const TRIGGER_TOOLBAR = 'TRIGGER_TOOLBAR';

export const FETCH_EMISSIONS = 'FETCH_EMISSIONS';
export const REQUEST_EMISSIONS = 'REQUEST_EMISSIONS';
export const RECEIVE_EMISSIONS = 'RECEIVE_EMISSIONS';
export const INVALIDATE_EMISSIONS = 'INVALIDATE_EMISSIONS';


export const RECEIVE_LATEST_AIR = 'RECEIVE_LATEST_AIR';
export const REQUEST_LATEST_AIR = 'REQUEST_LATEST_AIR';

export const FETCH_STATISTICS = 'FETCH_STATISTICS';
export const REQUEST_STATISTICS = 'REQUEST_STATISTICS';
export const RECEIVE_STATISTICS = 'RECEIVE_STATISTICS';

export const START_SIMULATION = 'START_SIMULATION';
export const REQUEST_SIMULATION = 'REQUEST_SIMULATION';
export const RECEIVE_SIMULATION = 'RECEIVE_SIMULATION';
export const SIMULATION_ERROR = 'SIMULATION_ERROR';
export const SET_SIMULATION_PARAMETERS = 'SET_SIMULATION_PARAMETERS';
export const SET_SINGLE_SIMULATION_PARAMETERS = 'SET_SINGLE_SIMULATION_PARAMETERS';

export const RECEIVE_PREDICTION = 'RECEIVE_PREDICTION';
export const RECEIVE_SINGLE_PREDICTION = 'RECEIVE_SINGLE_PREDICTION';
export const REQUEST_PREDICTION = 'REQUEST_PREDICTION';
export const INVALIDATE_PREDICTION = 'INVALIDATE_PREDICTION';

export const REQUEST_TRAFFIC = 'REQUEST_TRAFFIC';
export const FETCH_TRAFFIC = 'FETCH_TRAFFIC';
export const RECEIVE_TRAFFIC = 'RECEIVE_TRAFFIC';
export const INVALIDATE_TRAFFIC = 'INVALIDATE_TRAFFIC';

export const RECEIVE_CURRENT_BREMICKER = 'RECEIVE_CURRENT_BREMICKER';
export const SET_SELECTED_BOX = 'SET_SELECTED_BOX';